import { GlobalStyles } from 'Components/Page/styles'
import React from 'react'
import Head from 'next/head'
import { MainMenu } from 'Components/MainMenu'

interface PageProps {
  title: string
  children: React.ReactChildren | React.ReactChildren[] | React.ReactChild | React.ReactChild[]
}

const Page = ({ title, children }: PageProps) => {
  return (
    <div>
      <Head>
        <title>{`${title} | Herefeed`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <MainMenu />
      {children}
      <GlobalStyles />
    </div>
  )
}

export { Page }
